// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXgPYIoCkKKVk3T_DJA6VO3G1cJKAFH08',
    appId: '1:674233761214:web:2b0ad9de94552b79384def',
    messagingSenderId: '674233761214',
    projectId: 'my-project-a6545',
    authDomain: 'my-project-a6545.firebaseapp.com',
    storageBucket: 'my-project-a6545.firebasestorage.app',
    measurementId: 'G-J71TJ1K6D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8n9p1ZIb_iqt6YWHJvsMKXDQ0v9wxVIM',
    appId: '1:674233761214:android:e1a54391e41f651a384def',
    messagingSenderId: '674233761214',
    projectId: 'my-project-a6545',
    storageBucket: 'my-project-a6545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYCtxri_XxqML-GCwqNKumPr73g6soEaY',
    appId: '1:674233761214:ios:56968b0e5632f16a384def',
    messagingSenderId: '674233761214',
    projectId: 'my-project-a6545',
    storageBucket: 'my-project-a6545.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYCtxri_XxqML-GCwqNKumPr73g6soEaY',
    appId: '1:674233761214:ios:56968b0e5632f16a384def',
    messagingSenderId: '674233761214',
    projectId: 'my-project-a6545',
    storageBucket: 'my-project-a6545.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXgPYIoCkKKVk3T_DJA6VO3G1cJKAFH08',
    appId: '1:674233761214:web:39c84fabb4f98c7d384def',
    messagingSenderId: '674233761214',
    projectId: 'my-project-a6545',
    authDomain: 'my-project-a6545.firebaseapp.com',
    storageBucket: 'my-project-a6545.firebasestorage.app',
    measurementId: 'G-9EPB8YM3NK',
  );
}
